version: '3'
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
          - "80:80"
        volumes:
          - ./sites:/var/www
          - ./config/nginx:/etc/nginx/conf.d
          - ./data/logs:/var/log/nginx/
        depends_on:
          - php
          - db
    php:
        build:
          context: ./config/php
          dockerfile: Dockerfile
        container_name: php
        volumes:
          - ./sites:/var/www
          - ./config/php/php.ini:/usr/local/etc/php/php.ini
        ports:
          - "9000:9000"
    db:
        image: mariadb:latest
        container_name: db
        restart: unless-stopped
        ports:
          - '53003:3306'
        volumes:
          - ./data/mysql:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: secret
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
        depends_on:
            - db
